name: Docker Run
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: SSH to server
          uses: appleboy/ssh-action@master
          with:
            host: 64.226.118.126
            username: root
            password: cpasbi1Wesh
            run:
              cd /var/www/plex_iim && docker-compose pull
              cd /var/www/plex_iim && docker-compose down
              cd /var/www/plex_iim && docker-compose up -d




